### ISSUE TITLE
Proxy with v2

### ISSUE THREAD

**Issue by nhnkl159** [Laiteux/Milky#8]
Hey, i've been using Milky for own personal use and when i saw V2 came out i started making a checker with it, but i've noticed there is no proxy example, would you please explain me how to use proxy?

**Comment by Laiteux** [comment]
Hello, it depends on the web request API you use but since you're asking this I guess you're trying to use `HttpClient`.

You should learn how to use `HttpClient` before wanting to use it, as I'm not going to write code for you.

In order to avoid re-creating a new `HttpClient` instance with a different `HttpClientHandler` for each combo (which would consume a lot of CPU and slowdown the checker a lot), this is a trick you can use to reduce the count of `HttpClient` instances you will create to your proxies count.

https://stackoverflow.com/a/58216799/12094294

https://paste.mod.gg/ozayexaqej.cs

**Comment by Laiteux** [comment]
Now easy with Milky v3, it manages all of this stuff for you.
